/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET TIME_ZONE = '+00:00' */;

CREATE DATABASE IF NOT EXISTS butty;
CREATE USER IF NOT EXISTS butty@'%' IDENTIFIED BY 'butty';
GRANT ALL PRIVILEGES ON butty.* TO butty@'%';

FLUSH PRIVILEGES;

USE butty;
