version: '3.5'

## Development Environment with
## - App Dev Container
## - MariaDB Database Server
services:
  ## App Build Environment
  ## Docs: /developer-guide/
  butty:
    build: .
    image: butty
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "8000:8000"   # Default app port (host:container)
      - "40000:40000" # Go Debugger (host:container)
    shm_size: "2gb"

  ## MariaDB Database Server
  ## Docs: https://mariadb.com/docs/reference/cs10.6/
  mariadb:
    image: mariadb:10.6
    command: mysqld --port=4001 --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    expose:
      - "4001"
    ports:
      - "4001:4001" # Database port (host:container)
    volumes:
      - "./scripts/sql/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: butty
      MYSQL_USER: butty
      MYSQL_PASSWORD: butty
      MYSQL_DATABASE: butty

## Create shared "photoprism-develop" network for connecting with services in other docker-compose.yml files
networks:
  default:
    name: butty
    driver: bridge
