/*
 * url butty maker
 *
 * url butty maker
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"net/http"
	"url/internal/butty"
)

// ButtyUrlPost - create butty url
func ButtyUrlPost(c *gin.Context) {
	bs := butty.GetService()

	param := c.Param("url")
	bs.Logger.Debug("GET param", zap.String("url", param))

	buttyUrl, err := bs.Storage.NewButtyUrl(param)
	if err != nil {
		bs.Logger.Error("NewButtyUrl", zap.Error(err))
		c.JSON(http.StatusInternalServerError, gin.H{"message": "Error create butty link"})
		return
	}
	bs.Logger.Debug("GET return", zap.String("burl", buttyUrl))
	c.JSON(http.StatusOK, gin.H{"url": buttyUrl})
}

// ByButtyGet - redirect to url by butty
func ByButtyGet(c *gin.Context) {
	bs := butty.GetService()

	param := c.Param("url")
	bs.Logger.Debug("GET param", zap.String("burl", param))

	fullUrl, err := bs.Storage.GetFullUrlByButty(param)
	if err != nil {
		bs.Logger.Error("GetFullUrlByButty", zap.Error(err))
		c.JSON(http.StatusNotFound, gin.H{"message": "link not found"})
		return
	}
	bs.Logger.Debug("GET return", zap.String("url", fullUrl))
	c.JSON(http.StatusOK, gin.H{"url": fullUrl})
}
