/*
 * url butty maker
 *
 * url butty maker
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package url

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// ButtyUserIdUrlPost - create butty url
func ButtyUserIdUrlPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UrlGet - redirect to url by butty
func UrlGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
