/*
 * url butty maker
 *
 * url butty maker
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"url/cmd/url"
	"url/internal/butty"
)

func main() {
	bs := butty.NewButtyService()
	go bs.Run()

	router := url.NewRouter()
	err := router.Run(":80")
	if err != nil {

	}
}
