service:
  WorkersCount: 10
  LogLevel: debug
  LinksLivesDays: 30
server:
  http:
    port: 8000
    timeout: 1s
data:
  database:
    driver: mysql
#    driver: inmemory
    source: butty:butty@tcp(mariadb:4001)/butty
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
