service:
  WorkersCount: 10
  LogLevel: debug
  LinksLivesDays: 30
server:
  serverName: https://butty-url.herokuapp.com
  http:
    port: 8000
    timeout: 1s
data:
  database:
#    driver: mysql
    driver: inmemory
    source: butty:butty@tcp(mariadb:4001)/butty

