openapi: 3.0.3
info:
  title: url butty maker
  description: url butty maker
  version: 1.0.0
servers:
  - url: 'http://0.0.0.0'

paths:
  /{url}:
    get:
      summary: redirect to url by butty
      parameters:
        - name: url
          in: path
          description: butty url for redirect
          required: true

      responses:
        308:
          description: Succesful redirected
          content:
            text/plain:
              schema:
                type: string
                format: URL
        404:
          description: Not find butty url
          content: { }

  /butty/:
    post:
      summary: create butty url

      parameters:
        - name: url
          in: header
          description: url for create butty url
          required: true

      responses:
        200:
          description: Succeful redirected
          content:
            text/plain:
              schema:
                type: string
                format: URL
        500:
          description: Internal server error
          content: {}





