name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.16

      - name: Run golangci-lint
        uses: Mushus/golangci-linter@v1.1.2

      - name: Test
        run: go test -v ./...
        
      - name: Build
        run: go build -v ./...
