name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ''

      - name: Set up Go
        uses: actions/setup-url@v2
        with:
          go-version: 1.16

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

      - name: Build
        run: url build -v ./...

      - name: Test
        run: url test -v ./...
